### ISSUE TITLE
error with Make

### ISSUE THREAD

**Issue by ddreyer** [rupc/go-with-intel-sgx#3]
`make` and other such build commands do not work, `make cgo` works since the library has already been built and included in the repository. Can someone elaborate on how to build the Enclave and library?

**Comment by rupc** [comment]
I fixed this problem. You can check it by executing following codes.
```
git clone https://github.com/rupc/go-with-intel-sgx.git
cd go-with-intel-sgx/SampleCode/Cxx11SGXDemo
make clean
make
make cgo
```
